### ISSUE TITLE
The decoded string is wrong when vatRegistrationNumber length is 15 

### ISSUE THREAD

**Issue by dev-sahar** [axenda/zatca#1]
#### Issue description
When I increase the vatRegistrationNumber to 15 characters/numbers (which is the length of the vat registration number for my KSA company) the decoded string gets missed up.

#### Steps to reproduce the issue

1.  use this as a sample 
```
     const invoice = new Invoice({
        sellerName: 'شركة تجريبية',
        vatRegistrationNumber: '123456789135785',
        invoiceTimestamp: '2021-02-21T11:20:27.983Z',
        invoiceTotal: '2785.8',
        invoiceVatTotal: '361.8',
      })

      invoice.toBase64()
```
2.  then take the generated base64 string to https://www.base64decode.org/
3.  decode and check the results

#### What's the expected result?

a readable string similar to this

```
شركة تجريبية
1234567891357852021-02-21T11:20:27.983Z2785.8361.8
```

#### What's the actual result?

![image](https://user-images.githubusercontent.com/13395802/143477419-900956db-eb7c-4c18-acf2-5c92596819fa.png)

**Comment by ihadabs** [comment]
Hi @dev-sahar,

I'm gonna look at it tomorrow, if you can fix the issue, please create a pull request 🙌.

**Comment by ihadabs** [comment]
@dev-sahar 

I how did you asume that the result is invalid?
Just checked the output with the ZATCA SDK for the values you provided and it was decoded correctly.

<img width="1048" alt="CleanShot 2021-12-07 at 14 30 16@2x" src="https://user-images.githubusercontent.com/34512743/145021967-522f2df0-93d3-4df5-a367-2cf995ddebe2.png">

If we're missing somthing here, please, elaborate more.
