### ISSUE TITLE
Question about phase1

### ISSUE THREAD

**Issue by sudo-sand** [axenda/zatca#10]
Hi, I was wondering, if this is compatible with ZATCA phase 1?

Is this the invoice data I need to save in a DB?
```js
{
	sellerName: 'Axenda',
	vatRegistrationNumber: '1234567891',
	invoiceTimestamp: '2021-12-04T00:00:00Z',
	invoiceTotal: '100.00',
	invoiceVatTotal: '15.00',
}
```
Or do I save the qrCode base64?

**Comment by xBiei** [comment]
this is compatible with phase 1
it has all the requirements required by ZATCA.
and you don't have to store it in your db cuz it'll always be the same data if u didn't modify the receipt info
anyway the final qrcode value is in base64, so if you want to save it for some reason just save the base64 so u can generate the qrcode directly using the stored base64.

**Comment by xBiei** [comment]
also the invoice total must be VAT included
so in your case if it's a 100SR excluding VAT, it would be like this: 
```js
{
	sellerName: 'Axenda',
	vatRegistrationNumber: '1234567891',
	invoiceTimestamp: '2021-12-04T00:00:00Z',
	invoiceTotal: '115.00',
	invoiceVatTotal: '15.00',
}
```
