### ISSUE TITLE
Qr code doesn't repeat on multiple pages while printing a document.

### ISSUE THREAD

**Issue by farhankarim** [axenda/zatca#13]
Hi there,i am having an issue with my receipt printing code. My receipt is 12 pages and the qr code should repeat on each page as it is fixed on top of page.But it only renders once . Either first or last page. I cannot share the confidential document but i am attaching my code for fixed header which has the qr code in it.

`    .global-header{
        position: fixed;
        width: 100%;
        bottom: 0;
        left: 0;
        padding: 1em
      }
`

`<div className="global-header" style={{ display: "block", marginLeft: "auto", width: 180, height: 190 }} >
                                                    <QRCode value={qrBarcodeInvoice} size={180} />
                                                    </div>`

**Comment by ihadabs** [comment]
Hi @farhankarim,

This package would only generate the base image for the QR code.
I think you're having an issue with displaying it which is not related.

Closing the issue for now. If you have more details, you're welcome to open again.
