### ISSUE TITLE
Error: You need to specify a canvas element in React Native 

### ISSUE THREAD

**Issue by A7medSabry** [axenda/zatca#2]
Hi 
When trying to use 
const imageData = await invoice.render();
it's return Error: You need to specify a canvas element

**Comment by ihadabs** [comment]
Hi @A7medSabry,

Where are you running the code? Browser or server?
Please also provide full code snippet.

**Comment by A7medSabry** [comment]
Code run in debug mode on mobile app with metro bundler 
React Naitve
Code 
<img width="468" alt="Screen Shot 2021-12-07 at 2 09 33 PM" src="https://user-images.githubusercontent.com/43677120/145026776-58f64f98-7e73-400a-bcf8-ce9e7b64faa9.png">
:

**Comment by ihadabs** [comment]
Hey there @A7medSabry,

The render method uses the `toDataURL` from [node-qrcode](https://github.com/soldair/node-qrcode).
If its throwing an error then you could open an issure in their repo 🙌.

Not sure about React Native but you could still render the `invoice.toBase64()` using other available packages.
