### ISSUE TITLE
react-scripts  ^5.0.0 support (Buffer is not defined) 

### ISSUE THREAD

**Issue by mehroozak** [axenda/zatca#4]
After updating my existing project to react-scripts ^5.0.0 i have faced an error which is 

**Uncaught (in promise) ReferenceError: Buffer is not defined**

this is because of Buffer is removed in react-scripts ^5.0.0

the issue is in functions named [toHex, toTlv] at the time of creating new object of Invoice 

**Testing environment:**
- create-react-app
- node = 16.13.1
- react-scripts = 5.0.0
- npm version = 8.1.2

Thanks
![image](https://user-images.githubusercontent.com/40487920/152337387-cba09e34-2aef-46fe-827f-b9518426e5d1.png)

**Comment by marshadri** [comment]
This PR can help to resolve this issue 
https://github.com/axenda/zatca/pull/3
