### ISSUE TITLE
Zatca 2nd phase QR

### ISSUE THREAD

**Issue by Harisul44** [axenda/zatca#7]
We want to integrate zatca 2nd phase QR. Can you help us?

**Comment by ihadabs** [comment]
Hey @Harisul44,
PRs are welcome ^^

**Comment by Harisul44** [comment]
Dear E-Invoicing Solution Provider,

Zakat, Tax and Customs Authority (ZATCA) is pleased to announce the launch
of the E-Invoicing Developer Portal (Sandbox). The Sandbox can be used to
simulate the integration with ZATCA’s platform (Fatoora), to view the API
details and to verify the requirements of Phase Two (Integration Phase).

You may reach the portal through the following link:
https://sandbox.zatca.gov.sa/

Please note the following, in order to use the platform, users are required
to register and confirm their registration via email. Therefore, please
include ***@***.***” in your safe senders list, additionally, the
verification email may end-up in the junk folder in some cases.

You may preview the updated E-Invoicing requirements and provide your
feedback through Istitlaa Platform through the link:
https://istitlaa.ncc.gov.sa/ar/Finance/GAZT/EinvoicingImplementationResolution/Pages/default.aspx

Finally, we are pleased to receive your comments and inquiries via the
authority's unified phone: 19993, or through the official channels of the
Authority.

Zakat, Tax and Customs Authority
